project:
  type: website
  output-dir: docs
  resources:
    - "*.html"

website:
  title: "Malo Jan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: data.qmd
        text: Data
      #- href: documents/CV_Malo_Jan.pdf
        #text: CV

# On the right, add twitter, github, linkedin and email
    right:
    - icon: twitter
      href: https://twitter.com/malo_jn
    - icon: github
      href: https://github.com/malojan
    - icon: envelope
      href: malo.jan@sciencespo.fr
    - icon: linkedin
      href: https://www.linkedin.com/in/malo-jan-3021a913a
    - text: "{{< fa brands bluesky >}}"
      href: https://bsky.app/profile/malojan.bsky.social

format:
  html:
    theme: simplex
    css: styles.css
    toc: true


